service: nest-serverless-poc

plugins:
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
